### ISSUE TITLE
This setup doesn't set a DISPLAY for selenium

### ISSUE THREAD

**Issue by mastermindg** [Tomohiro/xvfb-selenium-server#2]
Any browsers lauunched inherit Selenium's display and there is none set in your scripts so it is failing.

**Comment by mastermindg** [comment]
This can be resolved by adding:

env DISPLAY=:0.0

to selenium.conf along with the SELENIUM_SERVER variable.

**Comment by Tomohiro** [comment]
Thanks for your report. I'll fix that.

**Comment by Tomohiro** [comment]
I've fixed.

P.S

This repository is not maintained lately. Because I'm using [SleniumHQ's docker images](https://registry.hub.docker.com/repos/selenium/) for testing at my work. 

Anyway, thanks for your report.

**Comment by mastermindg** [comment]
Thanks for that. I'm actually starting to use docker with openstack.

**Comment by Tomohiro** [comment]
:+1:
